package main

var langEn = LangMap{
	GeneralInformationTitle: "Status",
	GeneralInformationText: "Date: Day %2d, %2d:%02d             Wind Force: %1.1f Beaufort            Speed: %02.2f Knots        To Destination: %4.0f Miles\n" +
		"Hull integrity: [%03.2f%%](%v)         Sails integrity: [%3.2f%%](%v)            Flooding: [%3.2f%%](%v)          Goods Quality: [%3.2f%%](%v)",
	CrewAndJobsTitle:          "Crew and Tasks",
	JobIdle:                   "Have Rest      ",
	JobNavigating:             "Navigate       ",
	JobRepairingHull:          "Hull repair    ",
	JobRepairingSail:          "Sails repair   ",
	JobPumpingOutWater:        "Pump out water ",
	JobShootingCannons:        "Shoot cannons  ",
	OverviewTitle:             "Overview",
	DispatchMessage:           "You ship is roadworthy. Holds are full of goods. Crew is ready to cross the Atlantic. Set several sailors to navigate the ship.\n\nPress [F1] to see help about controls.",
	ShipIsStandingOverview:    "[The ship is anchored.](fg:yellow)\n",
	ShipGoesByOarsOverview:    "The ship goes on oars. ",
	ShipGoesBySailOverview:    "The ship is sailing. ",
	StormOutsideOverview:      "You are crossing the storm. ",
	NavigationTeamOptimalSize: "Optimal navigation crew size is %v sailors.\n",
	PerfCoralReefDescr:        "The ship is crossing coral reefs!",
	EventsTitle:               "Captain's Log",
	HullIsDamaged:             "New hull damage: %3.2f%%",
	SailsAreDamaged:           "New sail damage: %3.2f%%",
	LogMessage:                "Day %2d, %2d:%02d    %v",
	JourneyStarted:            "Adventure begins!",
	ShipIsFullyBroken:         "Ship got too much holes. It fell into pieces and sank.",
	ShipIsFullyFlooded:        "The ship sank being totally flooded and",
	JourneyEnded:              "[Your trip is over.](fg:blue) [F10] - one more time.",
	HullIsBrokenOverview:      "[Hull is damaged.](fg:red) It needs to be repaired to stop leaking.\n",
	SailIsBrokenOverview:      "[Sail is damaged.](fg:red) Sailing is less effective. Need repair.\n",
	ShipIsFloodedOverview:     "[Holds are flooded, goods are getting bad!](fg:red) Pump out the water.\n",
	ControlsHelp:              "You've finally read a ship crew management manual. Brief:\nPress [1]..[5], to assign task to a sailor.\nPress [Shift]+[1]..[Shift]+[5] to free a sailor from a task.\n[F10] restart game.",
	FoundBottleEmpty:          "You found a bottle in the sea. It's empty.",
	FoundBottleDjinn:          "You found a bottle in the sea. There is a Djinn inside. You made him free.",
	DjinnCase0:                "Djinn refused to grant you wishes, flew away and teared sails.",
	DjinnCase1:                "Djinn suddenly made a blow and damaged the hull.",
	DjinnCase2:                "Gjinn repairs you ship and improved your goods.",
	DjinnCase3:                "Ghinn is speeding up the sheep for 3 days.",
	DjinnCase4:                "Gjinn made your trip safe for two days.",
	ReachedDestination:        "You successfully reached the New World. Your income is [%v](fg:yellow) Doubloons!",
	PiratesAttacking:          "Pirates are attacking you!",
	PiratesShot:               "Pirates made a volley of guns.",
	PiratesDead:               "Pirates' ship is destroyed.",
	PiratesKilledSailor:       "Our sailor is dead!",
	FoundPiratesGoods:         "Among the remains of the pirates' ship you found some high-quality goods",
	FoundPiratesSurvivor:      "A survivor from pirates' ship joined your team.",
	YouShot:                   "You did successful volley of guns that damaged pirates' ship",
	Party:                     "One of sailors had a birthday. Barrel of rum was opened, nobody wants to work.",
	DrunkedDead:               "One of the sailors died in a drunken brawl.",
	GoodsQualityImproved:      "Goods quality improved on %3.2f%%",
	GoodsQualityReduced:       "Goods quality reduced on %3.2f%%",
	Trader:                    "You met the traders' ship and traded a bit.",
	TraderPositive:            "Goods has high quality as they said!",
	TraderNegative:            "Only later you noticed that goods were rancid.",
	Blow:                      "One of the sailors inadvertently smoked next to a barrel of gunpowder.",
	CrossAtlantic:             "Cross-Atlantic",
	PressAKey:                 "Press [E] for english or [R] for russian",
}
